theme: jekyll-theme-slate
title: Michael Cary [Google Scholar](https://scholar.google.com/citations?user=WiG-_48AAAAJ&hl=en) [Twitter](https://twitter.com/data_cats) [ResearchGate](https://www.researchgate.net/profile/Michael-Cary-3)
